# Msg defining all inmediate lane contacts and its attributes
planning_interfaces/LaneContact successor                   # Forward lane
planning_interfaces/LaneContact predecessor                 # Former lane
planning_interfaces/LaneContact left_neighbor               # Left Lane
planning_interfaces/LaneContact right_neighbor              # Right Lane
planning_interfaces/LaneContact successor_left_neighbor     # Left Lane of successor
planning_interfaces/LaneContact successor_right_neighbor    # Right Lane of successor
planning_interfaces/LaneContact predecessor_left_neighbor   # Left Lane of predecessor
planning_interfaces/LaneContact predecessor_right_neighbor  # Right Lane of predecessor
