# This service message is used to retrieve the current ENU reference used by the AD Map in order to transform between different coordinate systems when working with different HDMaps
---
sensor_msgs/NavSatFix enu_reference # HDMap ENU origin
